query_tokenizer:
  init:
    _target_: src.tokenizers.colbert.QueryTokenizer
    encoder: ${encoder.name}
    max_len: 32
    add_prefix_token: true

doc_tokenizer:
  init:
    _target_: src.tokenizers.colbert.DocTokenizer
    encoder: ${encoder.name}
    max_len: 128
    add_prefix_token: true