defaults:
  - model: bi_encoder
  - encoder: bert
  - tokenizer: default
  - criterion: cross_entropy
  - dataloader: default
  - trainer: default
  - training: default
  - scheduler: default
  - logging: default
  - callbacks: default
  - _self_
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 


general:
  seed: 42
  dataset: msmarco-passage
  
paths:
  global_outputs: outputs
  local_outputs: ${paths.global_outputs}/${general.dataset}
  model: ${paths.local_outputs}/${model.name}
  checkpoints: ${paths.model}/checkpoints
  data: ${paths.model}/data
  logs: ${paths.model}/logs
  runs: ${paths.model}/runs
  hyperparams: ${paths.model}/hyperparams


compile_mode: default  # Options are default, reduce-overhead, and max-autotune

hydra:
  output_subdir: ${paths.model}/hydra  
  run:  
    dir: .