name: bi_encoder_mean

config:
  _target_: src.models.BiEncoder
  language_model: ${language_model.name}
  normalize_embeddings: false
  learning_rate: ${training.learning_rate}
  logit_scale: 20.0
  position_embedding_type: absolute

params:
  language_model: ${language_model.name}
  normalize_embeddings: false
  learning_rate: ${training.learning_rate}
  logit_scale: 20.0
  position_embedding_type: absolute