name: bi_encoder_pooler

init:
  _target_: src.models.BiEncoder
  encoder: ${encoder.name}
  pooling_strategy: pooler
  normalize_embeddings: false
  share_weights: true
  learning_rate: ${training.learning_rate}
  logit_scale: 20.0

checkpoint:
  _target_: src.models.BiEncoder.load_from_checkpoint
  encoder: ${encoder.name}
  pooling_strategy: pooler
  normalize_embeddings: false
  share_weights: true
  learning_rate: ${training.learning_rate}
  logit_scale: 20.0