name: cross_encoder

init:
  _target_: src.models.CrossEncoder
  encoder: ${encoder.name}
  learning_rate: ${training.learning_rate}

checkpoint:
  _target_: src.models.CrossEncoder.load_from_checkpoint
  encoder: ${encoder.name}
  learning_rate: ${training.learning_rate}